SELECT "NEXT";
SELECT distance FROM distances WHERE dendrite_id = "1";
SELECT "NEXT";
SELECT distance FROM distances WHERE dendrite_id = "2";
SELECT "NEXT";
SELECT distance FROM distances WHERE dendrite_id = "3";
SELECT "NEXT";
SELECT distance FROM distances WHERE dendrite_id = "4";
SELECT "NEXT";
SELECT distance FROM distances WHERE dendrite_id = "5";
SELECT "NEXT";
SELECT distance FROM distances WHERE dendrite_id = "6";
SELECT "NEXT";
SELECT distance FROM distances WHERE dendrite_id = "7";
SELECT "NEXT";
SELECT distance FROM distances WHERE dendrite_id = "8";
SELECT "NEXT";
SELECT distance FROM distances WHERE dendrite_id = "9";
SELECT "NEXT";
SELECT distance FROM distances WHERE dendrite_id = "10";
